version: "3.8"

services:
  # FastAPIアプリケーション
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=FastAPI Docker Compose App
      - APP_VERSION=1.0.0
      - DEBUG=true
      - LOG_LEVEL=debug
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8080
    volumes:
      # 開発時のホットリロード用（オプション）
      - ./app.py:/app/app.py:ro
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import requests; requests.get('http://localhost:8000/health')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  # Nginx（リバースプロキシとして使用、オプション）
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi-app
    restart: unless-stopped

# ネットワーク設定
networks:
  default:
    driver: bridge

# ボリューム設定（必要に応じて）
volumes:
  app_data:
